const canvas=document.querySelector('#visualizer');const ctx=canvas.getContext('2d');const btn=document.querySelector('#listenBtn');const source=document.querySelector('#source');const empty=document.querySelector('#emptyState');const statusEl=document.querySelector('#status');const toast=document.querySelector('#toast');let audioContext,analyser,stream,raf,startedAt;
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function resize(){const dpr=devicePixelRatio||1;canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteTimeDomainData(data);ctx.beginPath();ctx.strokeStyle='#caff3d';ctx.lineWidth=1.5;ctx.shadowBlur=10;ctx.shadowColor='#caff3d';data.forEach((v,i)=>{const x=i/(data.length-1)*w,y=v/255*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.shadowBlur=0;const elapsed=Date.now()-startedAt;const d=new Date(elapsed);document.querySelector('#timecode').textContent=`${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}:${String(d.getUTCSeconds()).padStart(2,'0')}`;raf=requestAnimationFrame(draw)}
async function start(inputStream){audioContext=new AudioContext();analyser=audioContext.createAnalyser();analyser.fftSize=2048;audioContext.createMediaStreamSource(inputStream).connect(analyser);stream=inputStream;startedAt=Date.now();empty.classList.add('hidden');statusEl.classList.add('live');statusEl.innerHTML='<i></i>监听中';btn.classList.add('listening');btn.innerHTML='<span>■</span> 停止监听';document.querySelector('#sampleRate').textContent=`${(audioContext.sampleRate/1000).toFixed(1)} KHZ`;document.querySelector('#latency').textContent=`${Math.round((audioContext.baseLatency||.01)*1000)} MS`;draw();addActivity('音频源已连接')}
function stop(){cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());audioContext?.close();stream=null;empty.classList.remove('hidden');statusEl.classList.remove('live');statusEl.innerHTML='<i></i>待机';btn.classList.remove('listening');btn.innerHTML='<span>▶</span> 开始监听';document.querySelector('#latency').textContent='-- MS';document.querySelector('#sampleRate').textContent='-- KHZ'}
async function toggle(){if(stream)return stop();try{if(source.value==='file'){document.querySelector('#fileInput').click();return}const constraints=source.value==='mic'?{audio:true}:{video:true,audio:true};const s=source.value==='mic'?await navigator.mediaDevices.getUserMedia(constraints):await navigator.mediaDevices.getDisplayMedia(constraints);if(!s.getAudioTracks().length){s.getTracks().forEach(t=>t.stop());throw new Error('所选来源没有可用音轨')}await start(s)}catch(e){notify(e.message||'无法访问音频源')}}
function addActivity(label){const list=document.querySelector('#activityList');if(list.querySelector('.activity-empty'))list.innerHTML='';const row=document.createElement('div');row.className='activity-row';row.innerHTML=`<b>◉</b><span>${label}</span><time>${new Date().toLocaleTimeString('zh-CN',{hour12:false})}</time>`;list.prepend(row)}
btn.addEventListener('click',toggle);document.querySelector('#fileInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const audio=new Audio(URL.createObjectURL(file));audio.loop=true;audioContext=new AudioContext();analyser=audioContext.createAnalyser();const media=audioContext.createMediaElementSource(audio);media.connect(analyser);analyser.connect(audioContext.destination);await audio.play();stream={getTracks:()=>[],file:true};startedAt=Date.now();empty.classList.add('hidden');statusEl.classList.add('live');statusEl.innerHTML='<i></i>播放中';btn.classList.add('listening');btn.innerHTML='<span>■</span> 停止监听';document.querySelector('#sampleRate').textContent=`${(audioContext.sampleRate/1000).toFixed(1)} KHZ`;draw();addActivity(`载入 ${file.name}`)});document.querySelector('#connectBtn').onclick=()=>notify('正在搜索局域网客户端…');document.querySelector('#clearBtn').onclick=()=>{document.querySelector('#activityList').innerHTML='<div class="activity-empty"><span>⌁</span><p>还没有监听记录</p><small>识别到的音符和事件会出现在这里</small></div>';notify('记录已清空')};document.querySelectorAll('.nav-item[data-view]').forEach(item=>item.onclick=()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));item.classList.add('active');if(item.dataset.view!=='monitor')notify('此模块将在后续版本开放')});
